### ISSUE TITLE
Doc improvement: Kafka version

### ISSUE THREAD

**Issue by Xaelias** [omarsmak/kafka-consumer-lag-monitoring#10]
`Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic partitions.`
Just got this trying to run your tool.
I know we're running a rather old version of kafka. It would have been nice if the readme mentioned which version of kafka is supported :-)

Thanks!

**Comment by omarsmak** [comment]
Thanks a lot for reporting this and indeed, we will need to improve the documentation to mention the supported Kafka version. Just to confirm, which Kafka broker version do you run?

Thank you :)

**Comment by Xaelias** [comment]
0.10.1.1 on that specific broker :-)

**Comment by omarsmak** [comment]
I updated the README file. Thank you again for your suggestion :)
