### ISSUE TITLE
Env Var support for Kuberentes/orchestration

### ISSUE THREAD

**Issue by dr460neye** [omarsmak/kafka-consumer-lag-monitoring#14]
Hi there,

for a orchestration framework support, it would be best to have direct support for environment variables.
The idea:
When all relevant variables are set, the tool does not need start parameters.

At the moment i use the following workaround in my deployment.yaml

`args: ["-b", "$(BOOTSTRAP_SERVERS)","-m", "$(MODE)","-c", "$(CONSUMER_GROUPS)","-i", "$(POLL_INTERVAL)", "-p", "$(HTTP_PORT)"]`

**Comment by omarsmak** [comment]
Ah I see, this is a good idea! Thank you. Sure, we can add all these application arguments as environment variables as well, should be trivial to add.

**Comment by omarsmak** [comment]
@dr460neye there is an idea to have this Client as Kuberentes operator with a custom CRD (CRD will be all the configurations like bootstrap server .. etc.) 
https://github.com/omarsmak/kafka-consumer-lag-monitoring/issues/26
