### ISSUE TITLE
Log formatting support

### ISSUE THREAD

**Issue by dr460neye** [omarsmak/kafka-consumer-lag-monitoring#15]
Hi there,

support for log formats would be really helpful in an container orchestration world.
Mostly two thing are used. Either JSON format, or classic log format.
Right now its some kind of a mix of multiple formats due to the kafka default logging.

What do you think about that?

**Comment by omarsmak** [comment]
That is actually a good hint! If I recall, having something like JSON logging format simplifies scrapping the logs from the container, isn't? 
I am thinking if we make customizable through log4j properties file that can be supplied through env variable and some configurations through env variables as well if needed, WDYT?

**Comment by dr460neye** [comment]
I would think about both. Add either by mounting a configmap file as an option, or as an env var like: LOG_PATTER = Myregex(%VARX%)Myregex etc.

**Comment by omarsmak** [comment]
Sure. As always, a PR would be highly appreciated ;)
