### ISSUE TITLE
Support newly joined consumers and new topics without the need to restart the exporter

### ISSUE THREAD

**Issue by Shini31** [omarsmak/kafka-consumer-lag-monitoring#17]
Hi,

The exporter is not able to update the list of consumer group even if wildcard _*_ is setted for the _-c_ parameter.
`java -jar kafka-consumer-lag-monitoring-0.0.6-all.jar -f ssl-user-config.properties -c "*" -m "prometheus" -i 5000`

If I deploy a new app with a new consumer group, it will be a great move to not restart the exporter to have its metrics

Regards.

**Comment by omarsmak** [comment]
which Kafka version do you use here?

**Comment by Shini31** [comment]
kafka 2.12-2.3.1

**Comment by omarsmak** [comment]
I just want to clarify the issue here, so the main issue here, that if you deploy a new consumer, the running exporter won't pick it up as far as I understood, is that correct? If that is the case, this is actually an annoying limitation that the exporter need to be restarted to in order to re-bootstrap the admin client in order to refresh the consumer groups. I haven't really dive into a workaround but I hope I can do soon

**Comment by Shini31** [comment]
Yes that's the point

**Comment by omarsmak** [comment]
Yeah unfortunately all these issues are limitation from the AdminClient, I will try to crack a workaround for this annoying issue whenever I have some time availability.

**Comment by Shini31** [comment]
No problem. Thank you for considering this issue.

**Comment by omarsmak** [comment]
@Shini31 as promised, took a look, it turned out to be pretty simple. Now the it supports newly consumers as well, release will be soon

**Comment by Shini31** [comment]
Good news !
I'm available if there's a need for further testing.

**Comment by omarsmak** [comment]
That would be great! thanks a lot! I have released 0.0.7, please give it a shot and report any issues further https://github.com/omarsmak/kafka-consumer-lag-monitoring/releases/tag/0.0.7 
P/S: regarding the topic deletion, I haven't added it yet, please report it in a separate issue so I can take a look at it in the next release.

**Comment by Shini31** [comment]
LGTM!
