### ISSUE TITLE
Information about Kafka brokers connection

### ISSUE THREAD

**Issue by Shini31** [omarsmak/kafka-consumer-lag-monitoring#18]
Hi,

I have a question about the method used to connect to the Kafka brokers.
For example, if I lose a Kafka broker in my cluster, will it try again to connect to it, or is the connection permanently lost?

Regards.

**Comment by omarsmak** [comment]
Hey @Shini31  it uses the Kafka AdminClient to connect to the broker in order to fetch the consumer groups. Regarding the connectivity, AFAIK it relies on the AdminClient, hence if the AdminClient re-connect again (which I think it), it should re-connect as well on the next poll.
