### ISSUE TITLE
Extend LAG Stats on consumer level

### ISSUE THREAD

**Issue by brunmesco** [omarsmak/kafka-consumer-lag-monitoring#23]
We played a bit with your kafka consumer lag monitoring library and have been excited about it.

The only thing we are missing is data splited to consumer level. Sometimes only one consumer in a consumer group is lagging (for different reasons).
With consolidated data per topic al lag is visible, although you don't see which consumer is lagging. In a clustered environment usually consumer groups are spread over different nodes and they can behave differently.

Very much appreciate if you consider this extension

thanks, Bruno

**Comment by omarsmak** [comment]
It has been added, will be released in 0.0.8

**Comment by brunmesco** [comment]
Cool! Thank you very much!

**Comment by omarsmak** [comment]
@brunmesco 0.0.8 has been released. Please give it a try and report any issues. Thanks

**Comment by brunmesco** [comment]
I've tested it and it works perfect! Thank you once again!
