### ISSUE TITLE
Log4j vulnerable - upgrade to 2.17.1+

### ISSUE THREAD

**Issue by chrbrnracn** [omarsmak/kafka-consumer-lag-monitoring#32]
**Describe the bug**
The latest version of the consumer-lag-monitor is using log4j 2.13.3
Log4j had some serious security issues end of 2021. Refer to https://logging.apache.org/log4j/2.x/security.html
Only the current latest version 2.17.1 has no known security issues.

**To Reproduce**
1. Go to /gradle.properties
2. Check log4jSlf4jImplVersion (https://github.com/omarsmak/kafka-consumer-lag-monitoring/blob/cf1d3cf1b2ddaeabada53ec5bc64d095d340c977/gradle.properties#L10)

log4jSlf4jImplVersion is not vulnerable itself but pulls log4j-core as a dependency which is vulnerable.

**Expected behavior**
Log4j is updated to a non-vulnerable version (>=2.17.1)

**Desktop (please complete the following information):**
not relevant

**Smartphone (please complete the following information):**
not relevant

**Comment by omarsmak** [comment]
Thanks for reporting this, can you please send a PR with this change?

**Comment by chrbrnracn** [comment]
Here it is: https://github.com/omarsmak/kafka-consumer-lag-monitoring/pull/33

**Comment by chrbrnracn** [comment]
When will a release build with this fix be available?

**Comment by omarsmak** [comment]
Hey @chrbrnracn , I have released version 0.1.2 which includes this patch. Sorry for delay on this.
